services:
  db:
    image: postgres:15-alpine
    container_name: aroma_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_BACKEND_PASS: ${DB_BACKEND_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/db/init.sql

  backend:
    build: ./server
    container_name: aroma_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules # Evita que los nodos locales sobrescriban los del contenedor
    depends_on:
      - db
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: aroma_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # Evita que los nodos locales sobrescriban los del contenedor
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
